# Prepositions

## Instruction

Prepositions are words like "to", "in", "on", "from".

Here are some Arabic prepositions

| Arabic | English |
|:----------------|:---------|
|[إِلَىٰ]{.ar} [ilA]{.trn}  | to |
|[فِي]{.ar}  [fI]{.trn}   | in |
|[عَلَىٰ]{.ar} [ealA]{.trn} | on |
|[مِنْ]{.ar}  [min]{.trn}  | from |

Note that [إِلَىٰ]{.ar} and [عَلَىٰ]{.ar} end with [ىٰ]{.ar}: a [yaa]{.trn} with no dots and with a tiny [alif]{.trn} on top of it. This is pronounced like an [alif]{.trn}.

Prepositions come before nouns just like in English. Examples:

[إِلَىٰ المَسْجِد]{.ar}  
"to the masjid"

[فِي بَيْت]{.ar}  
"in a house"

[عَلَىٰ كِتَاب]{.ar}  
"on a book"

[مِنْ الوَلَد]{.ar}  
"from the boy"

::: {.infobox data-latex="{caution}"}
**NOTE TO INSTRUCTOR**

Notice that we are leaving the [sukUn]{.trn} on [مِنْ]{.ar} even when followed by a [همزة وصل]{.ar}. This is so as not to overburden the student. He may pronounce the phrase as [min al-walad]{.trn} instead of [mina l-walad]{.trn}.

Similarly, the student may pronounce [ilA al-masjid]{.trn} and [fI al-bayt]{.trn} instead of [ila l-masjid]{.trn} and [fi l-bayt]{.trn}.
:::

We can use prepositions in sentences with verbs as well:

[ذَهَبَ الوَلَد إلَىٰ البَيْت]{.ar}  
"The boy went to the house."

