#!/bin/sh
Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook', output_dir='docs')"
cp -R fonts _book/fonts
cp -R fonts docs
#Rscript -e "bookdown::render_book('index.Rmd','bookdown::epub_book')"
#Rscript -e "bookdown::render_book('index.Rmd','pdf_document')"
Rscript -e "bookdown::render_book('index.Rmd','bookdown::pdf_book')"

