#!/bin/sh
Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook')"
cp -R fonts _book/fonts
#Rscript -e "bookdown::render_book('index.Rmd','bookdown::epub_book')"
#Rscript -e "bookdown::render_book('index.Rmd','pdf_document')"

