---
title: "An Arabic course for non-native children"
author: "A brother"
documentclass: book
geometry:
# A4 2 pages per sheet draft
- paper=a5paper               # a5: 148.5 by 210mm
# final
#- paperwidth=156mm  #170mm
#- paperheight=234mm #244mm
- bindingoffset=4mm
- textwidth=114.8mm           # = (170 - 6)*0.7
- textheight=170.8mm          # = 244 * 0.7
- twoside
mainfont: Junicode
mainfontoptions: Numbers=OldStyle
fontsize: 10pt
polyglossia-lang:
  name: en
polyglossia-otherlangs:
  - name: arabic
fontfamilies:
  - name: \arabicfont
    font: Scheherazade New
    options: Script=Arabic,Scale=1.0
csquotes: true
output:
  bookdown::gitbook:
    #split_by: "section"
    pandoc_args: ["--lua-filter=trn.lua"]
    keep_md: yes
    css: mystyle.css
    config:
      toc:
        collapse: section
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: null
      search: yes
      fontsettings:
        theme: white
        family: serif
        size: 2
      sharing:
        facebook: yes
        github: no
        twitter: yes
        linkedin: yes
        weibo: no
        instapaper: no
        vk: no
        all: ['facebook', 'twitter', 'linkedin', 'weibo', 'instapaper']
      info: yes
  bookdown::pdf_book:
    number_sections: true
    pandoc_args: ["--lua-filter=trn.lua", "--columns=65"] # for forcing word wrap in pipe tables
    latex_engine: xelatex
    #template: default_latex_template.tex # with Brill font the PDF font is too large and this needs to be uncommented. includes and in_header should then be commented
    includes:
      in_header: "preamble.tex"
    keep_tex: true

---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = function() {
  if (knitr::is_latex_output()) 'latex' else 'pandoc'
})
```

# Introduction {-}

:::{lang=ar dir=rtl}
بسم الله الرحمن الرحيم  
الحمد لله والصلاة والسلام على نبينا محمد  
أشهد أن لا إله إلا الله وأشهد أن محمدا عبده ورسوله  
أما بعد:
:::

This course aims to teach Arabic to non-native speaking school children.

This is a work in progress and is currently incomplete. The development page is at: https://github.com/adamiturabi/arabic-for-kids

## Approach {-}

We will focus on basic grammar, vocabulary and comprehension. So for example, we will accept as correct:

[فَتَحَ الوَلَد بَاب وَذَهَبَ إِلَىٰ الحَديقَة]{.ar}  
[fataHa Eal-walad bAb wapahaba EilA Eal-HadIqah]{.trn}

rather than

[فَتَحَ الوَلَدُ بَابًا وَذَهَبَ إِلَى الحَديقَة]{.ar}  
[fataHa l-waladu bAban wapahaba Eila l-HadIqah]{.trn}

The reason for this is that our goal is for children to be able to parse sentences and read and write at a basic proficiency. Although case endings are essential for an in-depth understanding, and indeed for disambiguation from flexible word order ([ضَرَبَ عمرًا زيدٌ]{.ar}), we feel they are not imperative to understand sentences that follow normal word order. At this basic level, we fear that case endings will introduce additional complexity to a non-native speaking student.

Once the student is at a high-school or college level, they may take an [الآجرومية]{.ar} or similar course for a more complete study of the grammar.

We will however try to introduce the concept of inflection to the student. Perhaps the sound masculine plural inflection in the [marfooe]{.trn} vs other cases will be suitable for this since it is one of the more visible inflections in unvowelized text and the student will get accustomed to seeing it in his supplemental reading.

## Starting age {-}

Lesson 1 of this course should be suitable for a child of around 8 years of age.

## Pre-requisites {-}

The student should already know how to read fully vowelized Arabic at a beginner level, i.e., basic [fathah]{.trn}, [kasrah]{.trn}, [Dammah]{.trn}, [caddah]{.trn}, and long vowels. More complicated orthography, like [hamzat al-wasl]{.trn}, is not expected to be known. But it is assumed that the student is getting Quranic [tajwId]{.trn} instruction at the same time elsewhere.

## Instruction and drills {-}

Each lesson is to be instructed to the student with new vocabulary introduced.

This lesson is then reinforced by regular drills. The drills usually require the student to translate a few sentences from Arabic to English and English to Arabic.
 
